### ISSUE TITLE
Basic Order Tracker

### ISSUE THREAD

**Issue by duyng404** [duyng404/cafapp-returns#14]
Set up an Order Tracker at /tracker. Has to be logged in to access. For the basic version:

- [ ] Users connect to the tracker through websocket.
- [ ] ~On connect, the backend will look through all orders that is "trackable" of that user, and send message detailing the status of that order.~
- [ ] ~When an order changes status, send a message to the user though this tracker.~

"trackable" order means that it is placed but not delivered.

**Comment by lamngue** [comment]
Too hard for beginner =))

**Comment by duyng404** [comment]
it's only too hard if u don't read the docs

**Comment by duyng404** [comment]
assigning this to dpham: you're gonna help finish up with this issue. it will require you to learn a new technology: socket.io (not WebSocket, although they are familiar).

The goal is to have a page up at `/tracker` that will be like a chatroom with a chatbot and can keep user updated about when their order is about to arrive. This is quite complex, so I splitted it into small tasks.

Task 1: See the socket in action. Clone [cafapp-admin](https://github.com/duyng404/cafapp-admin) into a folder, then `npm i` to install and `npm start` to run. Navigate to `localhost:3000` to use it.

Try opening a new tab, place an order and see that the new order will appear in the queue in real time. The admin can "move up" the order to different stages.

The end goal of this order tracker is that whenever the admin move the order up, like say, from Prepping to Shipping, the chatbot would notify the user from the order tracker.

**Comment by duyng404** [comment]
Task 2: familiarize yourself with socket.io. Here are the necessary docs and what you should do with it:

- [socket.io main docs](https://socket.io/docs/). Read this first. This docs provide an example for a server-client setup, both using javascript. We would use the client portion in javascript, but the server will be golang. Your goal of reading this is simply to know what it is capable of. 
- (not really a docs but) [lam's socket.io project](https://github.com/lamngue/ChatBot-Socket) if you wanna take it out for a ride and try it to see with your own eyes how socket.io works. This repo is also helpful as a simple example right out of the official docs.
- Golang's implementation of the socketio server: [This link for github repo and examples](https://github.com/googollee/go-socket.io) ([and this link for its reference docs](https://godoc.org/github.com/googollee/go-socket.io)) Quite straightforward. The syntax is similar to the javascript counterpart.
- And then finally my implementation of the socket server in the folder `socket`. There are comments, but maybe they're not enough, so here are several paragraphs about it in high level description:

The `socket` package here will have a central `server` and hold a list of `adminClients`. When the order tracker is built, it should have a list of `userClients` as well. These two lists will serve the purpose of sending out messages: when a message is sent out, it will loop through the list (of admins or users) and tell each of them to send the message

The function init is quite big, because it define all the scenario that could happen to a connection in here. 

When there is an incoming connection:

- at first the server will only listen to the event "register". Because of socketio design, anyone can make a client and point it at our server and it will connect. This is a security issue, so we require that the connection registers itself first before doing anything else.
- the register event right now only authenticate admin. Basically, the frontend will have a token that only an admin user can get. It will send that token with the "register" event. We will validate that token. If everything is fine, we open up a lot more interaction options for the connection.
- after registering, save the relevant info into the `adminClient` list.
- after registering, the client can now send other events like `qfeed-commit-queue` etc. These events are for moving the order up through the queue.
- what about sending data to the client? the way we do that is a bit lòng vòng:
  - first we define the function for sending data, and *save that function to the client object* (`client.SendNewOrder`, `client.UpdateCurrentQueue`)
  - then we define another function outside of `init`. This function will loop through the `adminClient` list and invoke the previous function, one by one for each clients. (like `NewOrderPlaced()` and `updateQueueForEveryone()`)
  - we can then call these function outside of the socket package. Note how the `NewOrderPlaced()` is called from `orderHandlers.go`

the whole point of this task is to *understand* how socket works.

**Comment by duyng404** [comment]
Task 3: Authentication for user.

You can see that at `/tracker` there are already some HTML. You can choose either to continue work on that, or to rewrite 100%, or rewrite 50%, whatever.

For now let's not make a chat room just yet. Implement an auth system first.

- Find out how the admin users are getting the tokens (in `gorm/user.go`). Now you need to do similar function for users. Token for users should be different from tokens for admin. (as in, one cannot use a user token to get admin access and vice versa). For this, I think we need to create a new field in the `UserSocketToken` object, adding in an `is_admin` boolean. And then when it checks for valid token (there should be 2 different functions for validating admin *and* validating user), it also check if `is_admin` is true (or false).
- First the client has to obtain the token. Write an endpoint similar to admins' `/my-info` that will generate the token. This endpoint should be in the `api` group. Maybe name it `/obtain-socket-token`.
- The first thing the client do when the page is loaded is to make a GET request to this `/obtain-socket-token` to get the token.
- Once got the token, initiate a socket connection to the backend, sending event `'register-user'` and the token. If success, the client will simply receive the string `okbro`.

Where to look for examples?

- how to send a GET request to obtain token in the first place? might want to google `jquery send get request`
- client-side code of the admin authentication is in `cafapp-admin`, folder `src/utils/socket.js`. Note: the rest of the project is written in React, so you can't exactly copy 100%. Just use it as a guideline.

again, if theres any question ask me

more tasks will come when u finish some of these
